spring:
  application:
    name: datalineage-api-gateway
  cloud:
    gateway:
      routes:
        - id: metadata-service
          uri: lb://datalineage-metadata-service
          predicates:
            - Path=/api/metadata/**
        - id: lineage-service
          uri: lb://datalineage-lineage-service
          predicates:
            - Path=/api/lineage/**
        - id: discovery-service
          uri: lb://datalineage-discovery-service
          predicates:
            - Path=/api/discovery/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics